name: My Jekyll Website
remote_theme: pages-themes/hacker@v0.2.0
lsi: false
safe: true
source: neha362.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge